### ISSUE TITLE
Sometimes the Bot hard to solve 

### ISSUE THREAD

**Issue by mchlmntln** [Stelath/wordscapes-bot#1]
some words can't solve because of the shuffle. i need to shuffle the letters to detect to another forms of words. Hopefully have a improvement next update,  then some levels can't detect because of the white screen blended to the scenery and word pallet

**Comment by DeathWish808** [comment]
After messing around with this for about 8 hours over the weekend I found that "i" is consistently confused for "f". On the rare occasion "Q" is confused for "O". Sometimes restarting everything fixed it for the first puzzle and nails it then it goes downhill.

Changing the speed tends to make things worse and make it take up to 6 to infinity times to finish. I say infinity because sometimes it only sees 6 letters instead of 7.

"FAILED TOO MANY TIMES. ATTEMPTING VOLATILE CHARACTER OCR." It happens a lot and once it does it twice in the terminal it brings up the "i" like it's supposed to as well as a longer and better list of words that always works. That list should be brought up first.

It would be nice if after every 16 puzzles it would auto-click on the pop-up's "X" in between "levels" to close it. Otherwise, it gets hung up.

The self-promotion ads they have do the same thing, but if you could press space or something to pause the script and same to resume then that would be great.

The only other thing would be to have the OCR look at the "crossed out 3" by the star in the bottom left corner and if it's there then have the program not enter any 3-letter words.

**Comment by Stelath** [comment]
Currently I'm not working on this, but I'd be more than happy to implement that feature if I ever revisit this project. If you're feeling a bit savvy yourself I'd be more than happy to merge any pull requests with added updates or features!
